fix: remove invalid xml characters in post content
halo-sigs/plugin-feed pull request #8
Opened 2023-03-05 09:29 UTC by longjuan

Fixes https://github.com/halo-sigs/plugin-feed/issues/7

```release-note
去除文章内容中的xml非法字符
```

2023-03-05 09:31 UTC, longjuan commented
@ruibaby 有空试试这个行不行，我没办法复现文章

2023-03-10 03:18 UTC, JohnNiang requested changes

2023-03-10 03:18 UTC, JohnNiang commented on src/main/java/run/halo/feed/FeedServiceImpl.java
> +                                        .description(XmlCharUtils.removeInvalidXmlChar(contentWrapper.getContent()))
这里似乎可以直接用 `org.apache.commons.text.StringEscapeUtils#escapeXml11` 或者 `org.apache.commons.text.StringEscapeUtils#escapeXml10`。

2023-03-10 07:25 UTC, longjuan commented on src/main/java/run/halo/feed/FeedServiceImpl.java
> +                                        .description(XmlCharUtils.removeInvalidXmlChar(contentWrapper.getContent()))
escapeXml10会对`<>`这些符号也转义了，会导致rss阅读器出现转义字符，如图：
![1678433096310](https://user-images.githubusercontent.com/28662535/224250592-e7d45af8-4558-4a9e-bfd5-ced5d9aee645.jpg)

2023-03-10 07:27 UTC, longjuan commented on src/main/java/run/halo/feed/FeedServiceImpl.java
> +                                        .description(XmlCharUtils.removeInvalidXmlChar(contentWrapper.getContent()))
正常应该显示：
![1678433211478](https://user-images.githubusercontent.com/28662535/224250950-3337cb9c-710b-4bd9-a33c-e356d5f28851.jpg)

2023-03-10 07:29 UTC, longjuan commented on src/main/java/run/halo/feed/FeedServiceImpl.java
> +                                        .description(XmlCharUtils.removeInvalidXmlChar(contentWrapper.getContent()))
或者在内容输出为全文时不加CDATA，就可以使用escapeXml10。
但是我看 halo 1.x 就是全文和摘要都是用的CDATA，我怕后面还会不会出现什么转义方面的问题

2023-03-17 10:04 UTC, ruibaby reviewed
/lgtm

2023-03-17 10:04 UTC, ruibaby commented
cc @halo-sigs/halo

2023-03-17 10:38 UTC, guqing reviewed
/lgtm

2023-04-09 13:34 UTC, ruibaby approved these changes
/approve

2023-04-09 13:44 UTC, merged